### ISSUE TITLE
R matrix values

### ISSUE THREAD

**Issue by TaheraTT** [darylclimb/cvml_project#10]
Hi Daryl, 

i have gone through the approach and most of the things i am able to understand. But i am not able to figure out the R matrix values. Can you please explain how you got those values in the matrix. i.e what rotations are done along which axes to get that matrix.

It would be really helpful if i get how you got that matrix, so that i can make necessary changes for my dataset.

Thanks 
Best Regards
Tahera

**Comment by darylclimb** [comment]
Hi,

Can you point me to which script you are referring to.

**Comment by TaheraTT** [comment]
Ipm -> utils.py -> line 77 -> R matrix values

**Comment by darylclimb** [comment]
Thanks for this issue. I realize there was a bug in the matrix. I have updated it. It follows the coordinate system according to https://www.mathworks.com/help/driving/ug/coordinate-systems.html

Let me know if you are still having trouble understanding

**Comment by TaheraTT** [comment]
Hi,

Actually with previous R matrix itselfi was getting correct top view, but i didn't understand how u derived that matrix. I tried with this new matrix that you updated yesterday, its not giving proper top view.
Can you please look into this.

Best regards
Tahera

**Comment by darylclimb** [comment]
R is derived by the change from vehicle coordinate to camera coordinate. Which is similar to the link above. Is the coordinate system you have similar to the one I am using?
