### ISSUE TITLE
Correction in projection matrix

### ISSUE THREAD

**Issue by songarsh** [darylclimb/cvml_project#11]
https://github.com/darylclimb/cvml_project/blob/6e6ec4c3fab5e1f59c2cf4953ad1f9b1e18106d5/projections/lidar_camera_projection/utils.py#L74

In the attached def, we have the return statement:
https://github.com/darylclimb/cvml_project/blob/6e6ec4c3fab5e1f59c2cf4953ad1f9b1e18106d5/projections/lidar_camera_projection/utils.py#L84
According to the Math, the return statement must've been:
    proj_mat = P_cam_ref2velo @ R_ref2rect_inv 

Best,
songarsh

**Comment by darylclimb** [comment]
Hi sogarsh, good catch:) thanks
