### ISSUE TITLE
Questions regarding lidar2image transformation

### ISSUE THREAD

**Issue by wartek69** [darylclimb/cvml_project#13]
Hey,
Thank you for this repo!
I'm doing my best to understand the `lidar_camera_project.py` code and have some questions regarding it.
I took snippets of the code to make this question a bit more readable
**render_lidar_on_image function**

```
def render_lidar_on_image(pts_velo, img, calib, img_width, img_height):
    # projection matrix (project from velo2cam2)
    proj_velo2cam2 = project_velo_to_cam2(calib)

    # apply projection
    pts_2d = project_to_image(pts_velo.transpose(), proj_velo2cam2)

    # Filter lidar points to be within image FOV
    inds = np.where((pts_2d[0, :] < img_width) & (pts_2d[0, :] >= 0) &
                    (pts_2d[1, :] < img_height) & (pts_2d[1, :] >= 0) &
                    (pc_velo[:, 0] > 0)
                    )[0]

    # Filter out pixels points
    imgfov_pc_pixel = pts_2d[:, inds]

    # Retrieve depth from lidar
    imgfov_pc_velo = pts_velo[inds, :]
    imgfov_pc_velo = np.hstack((imgfov_pc_velo, np.ones((imgfov_pc_velo.shape[0], 1))))
    imgfov_pc_cam2 = proj_velo2cam2 @ imgfov_pc_velo.transpose()

    cmap = plt.cm.get_cmap('hsv', 256)
    cmap = np.array([cmap(i) for i in range(256)])[:, :3] * 255

    for i in range(imgfov_pc_pixel.shape[1]):
        depth = imgfov_pc_cam2[2, i]
        color = cmap[int(640.0 / depth), :]
        cv2.circle(img, (int(np.round(imgfov_pc_pixel[0, i])),
                         int(np.round(imgfov_pc_pixel[1, i]))),
                   2, color=tuple(color), thickness=-1)
    plt.imshow(img)
    plt.yticks([])
    plt.xticks([])
    plt.show()
    return img
```
1) In this function you first transform the lidar points to 2d space, then extract the indices to only have the 2d points that are inside our camera. I get stuck in understand what you are trying to achieve with
```
    imgfov_pc_velo = np.hstack((imgfov_pc_velo, np.ones((imgfov_pc_velo.shape[0], 1))))
    imgfov_pc_cam2 = proj_velo2cam2 @ imgfov_pc_velo.transpose()
```
First you add an extra dimension with just ones, which I don't quite understand.
Further you transform the pointcloud points that belong to the pixels back to 2d space, which I don't understand either.
Why are you doing these operations?

2)
You define depth as: `depth = imgfov_pc_cam2[2, i]`, so basically taking the 'z' coordinate of the pointcloud that is transformed into 2D space. This doesn't make any sense to me since you are trying to get a depth from 2d space and the z coordinate doesn't have a meaning in there (what should it even mean in a 2d space?). Furthermore that value can be less than 0 when debugging the code, which doesn't make any sense either. Shouldn't the depth be calculated like something like:
```
        x = imgfov_pc_velo[i, 0]
        y = imgfov_pc_velo[i, 1]
        z = imgfov_pc_velo[i, 2]
        depth = np.sqrt(x**2 + y**2 + z**2)
```

**project_to_image**
```
def project_to_image(points, proj_mat):
    """
    Apply the perspective projection
    Args:
        pts_3d:     3D points in camera coordinate [3, npoints]
        proj_mat:   Projection matrix [3, 4]
    """
    num_pts = points.shape[1]

    # Change to homogenous coordinate
    points = np.vstack((points, np.ones((1, num_pts))))
    points = proj_mat @ points
    points[:2, :] /= points[2, :]
    return points[:2, :]

```
3) In project_to_image you divide the transfomred x,y with the transformed z coordinate, why do you do this? Furthermore before transformation you add a dimension with ones, what's the purpose of this?

Hopefully you can help me out with these questions!
Kind regards
Alex

**Comment by darylclimb** [comment]
Hi @wartek69 

1. np.ones is to convert to homogenous coordinates (x, y, z, 1). The operation is to transform from lidar to cam2 coord. Not to 2d pixel space. This is to get depth in cam2 coordinate.

2. Same reasoning. cam2 coordinate. Not 2d space

3. This is perspective transformation https://www.cse.psu.edu/~rtc12/CSE486/lecture12.pdf

Hope this helps

**Comment by wartek69** [comment]
Hi @darylclimb,
Thank you for your fast response and linking the lecture, it gave me some insights!
I'll repeat just to check if my understandigs are correct:
`imgfov_pc_velo = np.hstack((imgfov_pc_velo, np.ones((imgfov_pc_velo.shape[0], 1))))` is the conversion to homogenous coordinates.
`imgfov_pc_cam2 = proj_velo2cam2 @ imgfov_pc_velo.transpose()` projects our pointcloud to the camera reference coordinates. It uses the camera intrinsics & camera-lidar extrinsics to do so. The result of this transformation is basically the X, Y, Z from the following picture.
 
![Screenshot from 2022-03-16 11-03-07](https://user-images.githubusercontent.com/26298408/158566073-c85d1f90-157e-4cf9-a760-2e023e50612d.png)

As seen in the picture, to get the actual pixel values we divide the X & Y by Z. This is basically retransforming back from the homogenous coordinates. I did not notice you using the focal length in `project_to_image` as shown on the screenshot from the lecture, but I suppose that is contained inside the projection matrix.
In this repo you use the Z to define the depth, which is basically the depth if you transform all the points to the ground plane. What I mean with that it is not the distance to the actual point which you would obtain by doing something like 
`distance = sqrt(X²+Y²+Z²)`

What I still do not understand is that whenever I change the calibration to my own calibration I'll get some negative values for the Z, which would basically mean that the points are behind the camera? (Points with a positive Z seem to be projected correctly from visual inspection) 
Does this mean that my calibration is incorrect and thus I'm getting these weird artifacts? 

Once again, thank you for providing all the useful information!
Kind regards
Alex

**Comment by darylclimb** [comment]
> imgfov_pc_cam2 = proj_velo2cam2 @ imgfov_pc_velo.transpose() projects our pointcloud to the camera reference coordinates. It uses the camera intrinsics & camera-lidar extrinsics to do so.

If you look at the parameters carefully, proj_velo2cam2 does not use camera intrinsic.

> What I still do not understand is that whenever I change the calibration to my own calibration I'll get some negative values for the Z, which would basically mean that the points are behind the camera? (Points with a positive Z seem to be projected correctly from visual inspection)
Does this mean that my calibration is incorrect and thus I'm getting these weird artifacts?

RIght, It is possible some of your lidar points are behind the camera.

**Comment by wartek69** [comment]
Hi @darylclimb 
proj_velo2cam2 uses the P2 matrix, which contains the camera intrinsics or am I missing something?

**Comment by darylclimb** [comment]
Hi @wartek69 
Sorry, I misread. Yes, you are right.
