### ISSUE TITLE
Projecting image to IPM

### ISSUE THREAD

**Issue by athus1990** [darylclimb/cvml_project#6]
Hi ! Thanks for the great work.

I had one question. Suppose I have a 2d point(x,y) on front image. I want to get the associated location [u,v] in the IPM(500x500) image.
I did [u,v]=[x,y,0,1]@intrinsics@extrinsics.
This doe not work.
Am I missing something?

**Comment by darylclimb** [comment]
Hi @athus1990 

Please see https://github.com/darylclimb/cvml_project/blob/d98e1d88fe9c1a0b46d42c15b5d993da9f573b88/projections/ipm/ipm.py#L10
for the correct implementation.
